CREATE DATABASE CourtageCoin
USE CourtageCoin

CREATE TABLE PAIS(
	PAI_INT_ID INT IDENTITY(1,1) NOT NULL,
	PAI_STRC_DESC VARCHAR(75) NOT NULL,
	PAI_STR_SIGLA CHAR(2) NOT NULL,
	CONSTRAINT UK_PAI_STR_SIGLA UNIQUE(PAI_STR_SIGLA),
	CONSTRAINT PK_PAI_INT_ID PRIMARY KEY CLUSTERED (PAI_INT_ID)
);
GO

CREATE TABLE ESTADO(
	EST_INT_ID INT IDENTITY(1,1) NOT NULL,
	EST_STR_DESC VARCHAR(75) NOT NULL,
	EST_STR_SIGLA CHAR(2) NOT NULL,
	PAI_INT_ID INT NOT NULL,
	CONSTRAINT UK_EST_STR_SIGLA UNIQUE(EST_STR_SIGLA),
	CONSTRAINT PK_EST_INT_ID PRIMARY KEY CLUSTERED (EST_INT_ID),
	CONSTRAINT FK_ESTADO_PAIS_INT_ID FOREIGN KEY (PAI_INT_ID) REFERENCES PAIS (PAI_INT_ID)
);
GO

CREATE TABLE CIDADE(
	CID_INT_ID INT IDENTITY(1,1) NOT NULL,
	CID_STR_DESC VARCHAR(75) NOT NULL,
	EST_INT_ID INT NOT NULL,
	CONSTRAINT PK_CID_INT_ID PRIMARY KEY CLUSTERED(CID_INT_ID),
	CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);
GO

CREATE TABLE ENDERECO(
	END_INT_ID INT IDENTITY(1,1) NOT NULL,
	END_STR_LOGRADOURO VARCHAR(75) NOT NULL,
	END_STR_NUMERO VARCHAR(4) NOT NULL,
	END_STR_BAIRRO VARCHAR(45) NOT NULL,
	END_STR_COMPLEMENTO VARCHAR(15) NULL,
	CID_INT_ID INT NOT NULL,
	CONSTRAINT PK_END_INT_ID PRIMARY KEY CLUSTERED(END_INT_ID),
	CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);
GO

CREATE TABLE PESSOA_FISICA(
	PEF_INT_ID INT IDENTITY(1,1) NOT NULL,
	PEF_STR_NOME VARCHAR(70) NOT NULL,
	PEF_STR_CPF VARCHAR(11) NOT NULL,
	PEF_DATE_NASCIMENTO DATE NOT NULL,
	END_INT_ID INT NOT NULL,
	CONSTRAINT PK_PEF_INT_ID PRIMARY KEY CLUSTERED(PEF_INT_ID),
	CONSTRAINT UK_PEF_STR_CPF UNIQUE(PEF_STR_CPF),
	CONSTRAINT FK_ENDERECO_PEF_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID)
);
GO

CREATE TABLE PESSOA_JURIDICA(
	PEJ_INT_ID INT IDENTITY(1,1) NOT NULL,
	PEJ_STR_CNPJ VARCHAR(14) NOT NULL,
	PEJ_INT_IM INT NULL,
	PEJ_INT_IE INT NOT NULL,
	PEJ_STR_RAZAO_SOCIAL VARCHAR(70),
	END_INT_ID INT NOT NULL,
	CONSTRAINT PK_PEJ_INT_ID PRIMARY KEY CLUSTERED(PEJ_INT_ID),
	CONSTRAINT UK_PEJ_STR_CNPJ UNIQUE(PEJ_INT_ID),
	CONSTRAINT UK_PEJ_INT_IE UNIQUE(PEJ_INT_IE),
	CONSTRAINT FK_ENDREECO_PEJ_INT_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID)
);
GO

CREATE TABLE SETOR(
	SET_INT_ID INT IDENTITY(1,1) NOT NULL,
	SET_STR_NOME VARCHAR(70) NOT NULL,
	CONSTRAINT PK_SET_INT_ID PRIMARY KEY CLUSTERED(SET_INT_ID)
);
GO

CREATE TABLE FUNCIONARIO(
	FUN_INT_ID INT IDENTITY(1,1) NOT NULL,
	FUN_INT_MATRICULA INT NOT NULL,
	FUN_STR_NOME VARCHAR(70) NOT NULL,
	SET_INT_ID INT NOT NULL,
	CONSTRAINT PK_FUN_INT_ID PRIMARY KEY CLUSTERED(FUN_INT_ID),
	CONSTRAINT UK_FUN_INT_MATRICULA UNIQUE(FUN_INT_MATRICULA),
	CONSTRAINT FK_SETOR_FUN_ID FOREIGN KEY(SET_INT_ID) REFERENCES SETOR(SET_INT_ID)
);
GO

CREATE TABLE USUARIO(
	USU_INT_ID INT IDENTITY(1,1) NOT NULL,
	USU_STR_LOGIN VARCHAR(20) NOT NULL,
	USU_STR_SENHA VARCHAR(10) NOT NULL,
	USU_INT_TELEFONE INT NULL,
	USU_STR_EMAIL VARCHAR(40) NOT NULL,
	USU_DATA_CADASTRO DATE NOT NULL,
	FUN_INT_ID INT NOT NULL,
	CONSTRAINT PK_USU_INT_ID PRIMARY KEY CLUSTERED(USU_INT_ID),
	CONSTRAINT UK_USU_STR_LOGIN UNIQUE(USU_STR_LOGIN),
	CONSTRAINT FK_FUN_USU_ID FOREIGN KEY(FUN_INT_ID) REFERENCES FUNCIONARIO(FUN_INT_ID)
);
GO

CREATE TABLE CLIENTE(
	CLI_INT_ID INT IDENTITY(1,1) NOT NULL,
	PEF_INT_ID INT NULL,
	PEJ_INT_ID INT NULL,
	CONSTRAINT PK_CLI_INT_ID PRIMARY KEY CLUSTERED(CLI_INT_ID),
	CONSTRAINT FK_CLI_PEF_INT_ID FOREIGN KEY(PEF_INT_ID) REFERENCES PESSOA_FISICA(PEF_INT_ID),
	CONSTRAINT FK_CLI_PEJ_INT_ID FOREIGN KEY(PEJ_INT_ID) REFERENCES PESSOA_JURIDICA(PEJ_INT_ID),
);
GO

CREATE TABLE CARTEIRA (
	CAR_INT_ID INT IDENTITY(1,1) NOT NULL,
	CAR_INT_NUM_CARTEIRA INT NULL,
	CAR_STR_NOME_ATIVO VARCHAR(45) NULL,
	CAR_INT_VALOR INT NULL,
	CLI_INT_ID  INT NOT NULL,
	CONSTRAINT PK_CAR_INT_ID PRIMARY KEY CLUSTERED(CAR_INT_ID),
	CONSTRAINT FK_CLI_CAR_INT_ID FOREIGN KEY(CLI_INT_ID) REFERENCES CLIENTE(CLI_INT_ID)
);
GO

CREATE TABLE TRANSACAO(
	TRA_INT_ID INT IDENTITY(1,1) NOT NULL,
	TRA_INT_COD INT NOT NULL,
	TRA_DATE_DATA DATE NOT NULL,
	TRA_STR_VALOR DECIMAL(13,2) NOT NULL,
	CAR_INT_ID INT NOT NULL,
	CLI_INT_ID INT NOT NULL,
	CONSTRAINT PK_TRA_INT_ID PRIMARY KEY CLUSTERED(TRA_INT_ID),
	CONSTRAINT UK_TRA_INT_COD UNIQUE(TRA_INT_COD),
	CONSTRAINT FK_CAR_INT_ID FOREIGN KEY(CAR_INT_ID) REFERENCES CARTEIRA(CAR_INT_ID),
	CONSTRAINT FK_CLI_TRA_INT_ID FOREIGN KEY(CLI_INT_ID) REFERENCES CLIENTE(CLI_INT_ID)
);
GO
